### ISSUE TITLE
텔레그램 Max retries exceeded with url 오류

### ISSUE THREAD

**Issue by yklovett** [acidpop/synobot#7]
0.6 업데이트 후, OTP 연동까지 잘 끝났는데
아래 오류 메시지 처럼 해당 URL로 너무많이 시도했다고 오류가 발생합니다.

그래서 텔레그램 메시지가 안오는데, 실제 다운로드 걸었던 숫자는 10개 내외입니다.
해결방법이 없을까요?
(텔레그램 bot정보는 ### 처리했습니다)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 218, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 695, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram.vendor.ptb_urllib3.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot46282###:AAF2vTc8eRTSbLNGkv7NllSEC3dM####/sendMessage (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa9c6d829b0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

**Comment by acidpop** [comment]
해당 오류는 다운로드 스테이션의 오류가 아닌 텔레그램 연동 부분 오류입니다.

방화벽 문제 또는 텔레그램 연동에 문제가 있는것으로 보입니다.

**Comment by yklovett** [comment]
방화벽 해외차단이 문제였네요
download station 에 접속되는 포트가 해외에서도 접속 가능해야 진행이되는군요...

감사합니다.

**Comment by acidpop** [comment]
텔레그램이 해외 서버랑 연동이 되는 구조다 보니 그런것 같네요
